/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTD2 (number 75), J2[8]/D11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_COLUMN_STROBE_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_COLUMN_STROBE_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_COLUMN_STROBE_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_COLUMN_STROBE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_COLUMN_STROBE_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_COLUMN_STROBE_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTD1 (number 74), J2[12]/D3[3]/D13/LEDRGB_BLUE
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTD0 (number 73), J2[6]/D10
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ROW_Q0_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q0_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q0_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ROW_Q0_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ROW_Q0_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ROW_Q0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTD5 (number 78), J2[4]/D9
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ROW_Q1_FGPIO FGPIOD             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q1_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ROW_Q1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ROW_Q1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ROW_Q1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORTA13 (number 33), J2[2]/D8
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ROW_Q2_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q2_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ROW_Q2_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ROW_Q2_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ROW_Q2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC8 (number 65), J1[14]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ROW_Q3_GREEN_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q3_GREEN_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q3_GREEN_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ROW_Q3_GREEN_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ROW_Q3_GREEN_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ROW_Q3_GREEN_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTA5 (number 31), J1[12]/D5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ROW_Q3_RED_FGPIO FGPIOA             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q3_RED_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ROW_Q3_RED_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ROW_Q3_RED_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ROW_Q3_RED_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ROW_Q3_RED_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
